# Alaz calls loglistener service
apiVersion: v1
kind: Service
metadata:
  name: kcd-client
  namespace: kcd
  annotations:
    # DNS: log-alaz.getanteon.com
    service.beta.kubernetes.io/azure-load-balancer-ipv4: "40.127.251.4" # Azure -> Public IP addresses -> anteon-alaz-backend-loglistener-ip. Give access to resource group, check: infra_as_code
    service.beta.kubernetes.io/azure-load-balancer-resource-group: anteon-staging-group
    service.beta.kubernetes.io/port_443_no_probe_rule: "true" # disable health check to prevent EOF error
spec:
  ports:
  - name: http
    protocol: TCP
    port: 443
    targetPort: 8080
  selector:
    app: kcd-client
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 173.245.48.0/20
  - 103.21.244.0/22
  - 103.22.200.0/22
  - 103.31.4.0/22
  - 141.101.64.0/18
  - 108.162.192.0/18
  - 190.93.240.0/20
  - 188.114.96.0/20
  - 197.234.240.0/22
  - 198.41.128.0/17
  - 162.158.0.0/15
  - 104.16.0.0/13
  - 104.24.0.0/14
  - 172.64.0.0/13
  - 131.0.72.0/22
  - 2400:cb00::/32
  - 2606:4700::/32
  - 2803:f800::/32
  - 2405:b500::/32
  - 2405:8100::/32
  - 2a06:98c0::/29
  - 2c0f:f248::/32